trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'production'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      echo "Installing dependencies..."
      npm ci
    displayName: 'Install dependencies with npm ci'

  - script: |
      echo "Linting code..."
      npm run lint
    displayName: 'Run ESLint'

  - script: |
      echo "Building Next.js app..."
      npm run build
    displayName: 'Build Next.js App'
